# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'

# Set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -g default-terminal "tmux-256color"

# Change tmux prefix to Ctrl + a
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Tmux Detach
unbind t
bind-key t run-shell "bash ~/scripts/tmux_detach >> /dev/null" 

# Change Prefix + . to swap panes
unbind-key .
bind-key . command-prompt -p "Swap with target window:" \
"run-shell 'tmux swap-window -s $(tmux display-message -p \"#I\") -t %1 && tmux select-window -t %1'"

# Retain cwd
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Keymap for join-pane
bind-key J if-shell -F '#{?#{pane_marked_set},1,0}' \
    'join-pane -v -s "{marked}"' \
    'choose-window "join-pane -v -s \"%%\""'

# Use vi keys in copy mode
setw -g mode-keys vi
unbind-key -T copy-mode-vi v
unbind-key -T copy-mode-vi Space
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle; send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T prefix v copy-mode

# General Settings
set -g status-keys vi
set -g set-clipboard on
set -g mouse on
set -g status-interval 3 
set -g detach-on-destroy off
set -g base-index 1
set -g pane-base-index 1

# Reload config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"

# Yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

#======================================================================================

bg="#3A3A3A"
default_fg="#c5c9c5" 

# Status bar
set -g status-style bg=default
set -g status-fg colour245     # White text color
set-option -g status-position bottom
set -g status-left "#[fg=default, bold, bg=default] #S "
set -g status-right ""
set -g window-status-format "#[fg=default,bg=default] #I:#W"
set -g window-status-current-format "#[fg=${default_fg},bold, bg=default] #I:#W"
set -g window-status-last-style "fg=default,bg=default"

# Border Style
set -g pane-border-style "fg=#272727,bg=default"
set -g pane-active-border-style "fg=${bg},bg=default"

set -g message-command-style "bg=default,fg=${default_fg}"
set -g message-style "bg=default,fg=${default_fg}"

#======================================================================================

# Resize panes like in Vim
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Vim Tmux navigation
set -g @vim_navigator_prefix_mapping_clear_screen ""

vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

run '~/.tmux/plugins/tpm/tpm'

