$terminal = wezterm
$browser = qutebrowser

source = ./config/keymaps.conf
source = ./config/hardware.conf
source = ./config/appearance.conf
source = ./config/workspaces.conf

### Autostart
exec-once = nm-applet & swaync & blueman-applet & hyprpaper & hyprpolkitagent
exec-once = ./scripts/launch-waybar.sh
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 
exec-once = systemctl --user start hyprpolkitagent

### Environment variables 
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Adwaita

# Permissions 
# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
