wallpaper {
    monitor = DP-2
    path = /home/eulogio/.config/hypr/baguio.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-2
    path = /home/eulogio/.config/hypr/baguio.jpg
    fit_mode = cover
}
