### Hardware

# Home Laptop Setup
monitor = HDMI-A-1, 2560x1440@120, 0x1440, 1
monitor = desc:Xiaomi Corporation Mi Monitor 5833410036287 , 1920x1080@120, 2560x1440 , 1
monitor = eDP-2, 1920x1200@165, auto, 1
# monitor = eDP-2, disable
# monitor = eDP-2, 1920x1200@165, 4480x0, 1

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape 
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
         natural_scroll = true 
    }
}

gestures { 
    # workspace_swipe = true 
}

device { 
}

