### Hardware

# Home Laptop Setup
monitor = desc:Xiaomi Corporation Mi Monitor 5833410036287 , 1920x1080@120, 0x0, 1
monitor = eDP-2, 1920x1200@165, 0x1080, 1
# monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1

# Work Setup
# monitor = desc:Samsung Electric Company S22F350 H4ZN301749, 1920x1080@60, 0x0, 1
# monitor = HDMI-A-2, 1920x1080@100, 1920x0, 1

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape 
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
         natural_scroll = true 
    }
}

gestures { 
    # workspace_swipe = true 
}

device { 
}

