### Windows and Workspaces 
dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = slave
}

# Gemini scratchpad
workspace = special:gemini, on-created-empty:wezterm start tmux new-session -As gemini 'gemini', gapsout:10
workspace = special:todo, on-created-empty:wezterm start tmux new-session -As todo 'nvim ~/projects/todo/todo.md', gapsout:20
workspace = special:nixsearch, on-created-empty:qutebrowser --target window 'https://search.nixos.org/packages', gapsout:10