### Windows and Workspaces 
dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = slave
}

# Gemini scratchpad
workspace = special:gemini, on-created-empty:wezterm start tmux new-session -As gemini 'cd $(fd --hidden --type d . ~ | fzf --tmux) && gemini', gapsout:10
workspace = special:opencode, on-created-empty:wezterm start tmux new-session -As opencode 'cd $(fd --hidden --type d . ~ | fzf --tmux) && opencode', gapsout:10
workspace = special:todo, on-created-empty:wezterm start tmux new-session -As todo 'nvim ~/projects/todo/todo.md', gapsout:20
workspace = special:nixsearch, on-created-empty:qutebrowser --target window 'https://search.nixos.org/packages', gapsout:10

# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]

# Add border to special workspaces
windowrule = bordersize 2, onworkspace:special:gemini
windowrule = bordersize 2, onworkspace:special:todo
windowrule = bordersize 2, onworkspace:special:nixsearch
windowrule = bordersize 2, onworkspace:special:opencode

# windowrule = float, title:^gemini-scratchpad$
# windowrule = size 80% 80%, title:^gemini-scratchpad$
# windowrule = center, title:^gemini-scratchpad$

windowrule = suppressevent maximize, class:.*

# Make File Manager Floating
windowrulev2 = float, class:^(org.gnome.Nautilus)$
windowrulev2 = float, class:^(xdg-desktop-portal-gnome)$ 

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = noblur, class:^(rofi)$ 

# Wayland Video Bridge White Box
windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$ 
windowrulev2 = noanim, class:^(xwaylandvideobridge)$ 
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$ 
windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$ 
windowrulev2 = noblur, class:^(xwaylandvideobridge)$ 
windowrulev2 = nofocus, class:^(xwaylandvideobridge)$
