### Windows and Workspaces 
dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = slave
}

# Scratchpads
workspace = special:opencode, on-created-empty:wezterm start tmux new-session -As opencode 'opencode $(fd --hidden --type d --max-depth 3 . ~ | fzf --tmux || echo '~') && ', gapsout:20 
workspace = special:todo, on-created-empty:wezterm start tmux new-session -As todo 'nvim ~/projects/todo/todo.md', gapsout:20
workspace = special:nixsearch, on-created-empty:qutebrowser --target window 'https://search.nixos.org/packages', gapsout:10

# "Smart Borders"
workspace = w[t1],  border:false
workspace = w[tg1], border:false
workspace = f[1],  border:false
    
# Add border to special workspaces
# windowrule = border_size 2, match: workspace special:todo
# windowrule = border_size 2, onworkspace:special:nixsearch
# windowrule = border_size 2, onworkspace:special:opencode

# windowrule = suppressevent maximize, class:.*

# Make File Manager Floating
windowrule = float on, match:class ^(org.gnome.Nautilus)$
windowrule = float on, match:class ^(xdg-desktop-portal-gnome)$ 
windowrule = float on, match:class setup.temp

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
# windowrule = noblur, class:^(rofi)$ 

# # Wayland Video Bridge White Box
# windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$ 
# windowrulev2 = noanim, class:^(xwaylandvideobridge)$ 
# windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$ 
# windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$ 
# windowrulev2 = noblur, class:^(xwaylandvideobridge)$ 
# windowrulev2 = nofocus, class:^(xwaylandvideobridge)$
